title: Cadisha | Bioinfo & Data Engineer
description: Spatial Omics & Data Engineering for Health
remote_theme: pages-themes/minimal@v0.2.0 # Base propre et pro
google_analytics: # Ajoutez votre ID si besoin
show_downloads: false

# Personnalisation
author: Cadisha
email: sainthilaire.cadisha@exemple.com
linkedin_username: Cadisha Saint-Hilaire
github_username: CSaint-Hilaire

# Plugins pour un rendu propre
plugins:
  - jekyll-seo-tag
